SET IDENTITY_INSERT [dbo].[tblReport] ON
delete from [dbo].[tblReport]
INSERT INTO [dbo].[tblReport]
           ( [fldID]
		   ,[fldName]
           ,[fldTitle]
           ,[fldHeadTitle]
           ,[fldQuery]
           ,[fldGroupName]
           ,[fldIntialize]
           ,[fldPerLineIntialize]
           ,[fldShowAllColumns]
           ,[fldDesignID]
           ,[fldSpecial]
           ,[fldSpecialPattern]
           ,[fldFootTitle]
           ,[fldQueryTitle]
           ,[fldBorder]
           ,[fldTableCSSClass]
           ,[fldStyle]
           ,[fldTokenEncrypt]
           ,[fldScript]
           ,[fldShowSQLError]
           ,[fldUserReorder]
           ,[fldTrStyle]
           ,[fldSelectRow]
           ,[fldMulitpleSelect]
           ,[fldKeyField]
           ,[fldPrintHeadTitle]
           ,[fldPrintFootTitle]
           ,[fldSettingHidden]
           ,[fldProgram]
           ,[fldPrintUseHeader]
           ,[fldEndLinePage]
           ,[fldEndLine]
           ,[fldExportEnable]
           ,[fldRightClick]
           ,[fldExportDefault])
		   SELECT TOP (1000) [fldID]
      ,[fldName]
      ,[fldTitle]
      ,[fldHeadTitle]
      ,[fldQuery]
      ,[fldGroupName]
      ,[fldIntialize]
      ,[fldPerLineIntialize]
      ,[fldShowAllColumns]
      ,[fldDesignID]
      ,[fldSpecial]
      ,[fldSpecialPattern]
      ,[fldFootTitle]
      ,[fldQueryTitle]
      ,[fldBorder]
      ,[fldTableCSSClass]
      ,[fldStyle]
      ,[fldTokenEncrypt]
      ,[fldScript]
      ,[fldShowSQLError]
      ,[fldUserReorder]
      ,[fldTrStyle]
      ,[fldSelectRow]
      ,[fldMulitpleSelect]
      ,[fldKeyField]
      ,[fldPrintHeadTitle]
      ,[fldPrintFootTitle]
      ,[fldSettingHidden]
      ,[fldProgram]
      ,[fldPrintUseHeader]
      ,[fldEndLinePage]
      ,[fldEndLine]
      ,[fldExportEnable]
      ,[fldRightClick]
      ,[fldExportDefault]
  FROM [KosarWebDBBank].[dbo].[tblReport]
  where fldGroupName='ê“«—‘ ”«“'

SET IDENTITY_INSERT [dbo].[tblReport] OFF